In [152]:
import numpy as np
import pandas as pd
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
import matplotlib.pyplot as plt

In [153]:
df=pd.read_excel(r'C:\Users\Siddhant\Desktop\mush.xlsx')
df


class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0        p         x           s         n       t    p               f   
1        e         x           s         y       t    a               f   
2        e         b           s         w       t    l               f   
3        p         x           y         w       t    p               f   
4        e         x           s         g       f    n               f   
...    ...       ...         ...       ...     ...  ...             ...   
8119     e         k           s         n       f    n               a   
8120     e         x           s         n       f    n               a   
8121     e         f           s         n       f    n               a   
8122     p         k           y         n       f    y               f   
8123     e         x           s         n       f    n               a   

     gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
0               c         n          k  ...                        s   
1               c         b          k  ...                        s   
2               c         b          n  ...                        s   
3               c         n          n  ...                        s   
4               w         b          k  ...                        s   
...           ...       ...        ...  ...                      ...   
8119            c         b          y  ...                        s   
8120            c         b          y  ...                        s   
8121            c         b          n  ...                        s   
8122            c         n          b  ...                        k   
8123            c         b          y  ...                        s   

     stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                         w                      w         p          w   
1                         w                      w         p          w   
2                         w                      w         p          w   
3                         w                      w         p          w   
4                         w                      w         p          w   
...                     ...                    ...       ...        ...   
8119                      o                      o         p          o   
8120                      o                      o         p          n   
8121                      o                      o         p          o   
8122                      w                      w         p          w   
8123                      o                      o         p          o   

     ring-number ring-type spore-print-color population habitat  
0              o         p                 k          s       u  
1              o         p                 n          n       g  
2              o         p                 n          n       m  
3              o         p                 k          s       u  
4              o         e                 n          a       g  
...          ...       ...               ...        ...     ...  
8119           o         p                 b          c       l  
8120           o         p                 b          v       l  
8121           o         p                 b          c       l  
8122           o         e                 w          v       l  
8123           o         p                 o          c       l  

[8124 rows x 23 columns]

In [154]:
df.shape

(8124, 23)

In [155]:
df.dtypes

class                       object
cap-shape                   object
cap-surface                 object
cap-color                   object
bruises                     object
odor                        object
gill-attachment             object
gill-spacing                object
gill-size                   object
gill-color                  object
stalk-shape                 object
stalk-root                  object
stalk-surface-above-ring    object
stalk-surface-below-ring    object
stalk-color-above-ring      object
stalk-color-below-ring      object
veil-type                   object
veil-color                  object
ring-number                 object
ring-type                   object
spore-print-color           object
population                  object
habitat                     object
dtype: object

In [156]:
df.columns

Index(['class', 'cap-shape', 'cap-surface', 'cap-color', 'bruises', 'odor',
       'gill-attachment', 'gill-spacing', 'gill-size', 'gill-color',
       'stalk-shape', 'stalk-root', 'stalk-surface-above-ring',
       'stalk-surface-below-ring', 'stalk-color-above-ring',
       'stalk-color-below-ring', 'veil-type', 'veil-color', 'ring-number',
       'ring-type', 'spore-print-color', 'population', 'habitat'],
      dtype='object')

In [157]:
df.nunique()

class                        2
cap-shape                    6
cap-surface                  4
cap-color                   10
bruises                      2
odor                         9
gill-attachment              2
gill-spacing                 2
gill-size                    2
gill-color                  12
stalk-shape                  2
stalk-root                   5
stalk-surface-above-ring     4
stalk-surface-below-ring     4
stalk-color-above-ring       9
stalk-color-below-ring       9
veil-type                    1
veil-color                   4
ring-number                  3
ring-type                    5
spore-print-color            9
population                   6
habitat                      7
dtype: int64

In [158]:
from sklearn.preprocessing import LabelEncoder

In [159]:
le=LabelEncoder()
df['class']=le.fit_transform(df['class'])
df['cap-shape']=le.fit_transform(df['cap-shape'])
df['cap-surface']=le.fit_transform(df['cap-surface'])
df['cap-color']=le.fit_transform(df['cap-color'])
df['bruises']=le.fit_transform(df['bruises'])
df['odor']=le.fit_transform(df['odor'])
df['gill-attachment']=le.fit_transform(df['gill-attachment'])
df['gill-spacing']=le.fit_transform(df['gill-spacing'])
df['gill-size']=le.fit_transform(df['gill-size'])
df['gill-color']=le.fit_transform(df['gill-color'])
df['stalk-shape']=le.fit_transform(df['stalk-shape'])
df['stalk-root']=le.fit_transform(df['stalk-root'])
df['stalk-surface-above-ring']=le.fit_transform(df['stalk-surface-above-ring'])
df['stalk-surface-below-ring']=le.fit_transform(df['stalk-surface-below-ring'])
df['stalk-color-above-ring']=le.fit_transform(df['stalk-color-above-ring'])
df['stalk-color-below-ring']=le.fit_transform(df['stalk-color-below-ring'])
df['veil-type']=le.fit_transform(df['veil-type'])
df['veil-color']=le.fit_transform(df['veil-color'])
df['ring-number']=le.fit_transform(df['ring-number'])
df['ring-type']=le.fit_transform(df['ring-type'])
df['spore-print-color']=le.fit_transform(df['spore-print-color'])
df['population']=le.fit_transform(df['population'])
df['habitat']=le.fit_transform(df['habitat'])
df



class  cap-shape  cap-surface  cap-color  bruises  odor  \
0         1          5            2          4        1     6   
1         0          5            2          9        1     0   
2         0          0            2          8        1     3   
3         1          5            3          8        1     6   
4         0          5            2          3        0     5   
...     ...        ...          ...        ...      ...   ...   
8119      0          3            2          4        0     5   
8120      0          5            2          4        0     5   
8121      0          2            2          4        0     5   
8122      1          3            3          4        0     8   
8123      0          5            2          4        0     5   

      gill-attachment  gill-spacing  gill-size  gill-color  ...  \
0                   1             0          1           4  ...   
1                   1             0          0           4  ...   
2                   1             0          0           5  ...   
3                   1             0          1           5  ...   
4                   1             1          0           4  ...   
...               ...           ...        ...         ...  ...   
8119                0             0          0          11  ...   
8120                0             0          0          11  ...   
8121                0             0          0           5  ...   
8122                1             0          1           0  ...   
8123                0             0          0          11  ...   

      stalk-surface-below-ring  stalk-color-above-ring  \
0                            2                       7   
1                            2                       7   
2                            2                       7   
3                            2                       7   
4                            2                       7   
...                        ...                     ...   
8119                         2                       5   
8120                         2                       5   
8121                         2                       5   
8122                         1                       7   
8123                         2                       5   

      stalk-color-below-ring  veil-type  veil-color  ring-number  ring-type  \
0                          7          0           2            1          4   
1                          7          0           2            1          4   
2                          7          0           2            1          4   
3                          7          0           2            1          4   
4                          7          0           2            1          0   
...                      ...        ...         ...          ...        ...   
8119                       5          0           1            1          4   
8120                       5          0           0            1          4   
8121                       5          0           1            1          4   
8122                       7          0           2            1          0   
8123                       5          0           1            1          4   

      spore-print-color  population  habitat  
0                     2           3        5  
1                     3           2        1  
2                     3           2        3  
3                     2           3        5  
4                     3           0        1  
...                 ...         ...      ...  
8119                  0           1        2  
8120                  0           4        2  
8121                  0           1        2  
8122                  7           4        2  
8123                  4           1        2  

[8124 rows x 23 columns]

In [160]:
y=df['class']
x=df.drop('class',axis=1)

In [161]:
x

cap-shape  cap-surface  cap-color  bruises  odor  gill-attachment  \
0             5            2          4        1     6                1   
1             5            2          9        1     0                1   
2             0            2          8        1     3                1   
3             5            3          8        1     6                1   
4             5            2          3        0     5                1   
...         ...          ...        ...      ...   ...              ...   
8119          3            2          4        0     5                0   
8120          5            2          4        0     5                0   
8121          2            2          4        0     5                0   
8122          3            3          4        0     8                1   
8123          5            2          4        0     5                0   

      gill-spacing  gill-size  gill-color  stalk-shape  ...  \
0                0          1           4            0  ...   
1                0          0           4            0  ...   
2                0          0           5            0  ...   
3                0          1           5            0  ...   
4                1          0           4            1  ...   
...            ...        ...         ...          ...  ...   
8119             0          0          11            0  ...   
8120             0          0          11            0  ...   
8121             0          0           5            0  ...   
8122             0          1           0            1  ...   
8123             0          0          11            0  ...   

      stalk-surface-below-ring  stalk-color-above-ring  \
0                            2                       7   
1                            2                       7   
2                            2                       7   
3                            2                       7   
4                            2                       7   
...                        ...                     ...   
8119                         2                       5   
8120                         2                       5   
8121                         2                       5   
8122                         1                       7   
8123                         2                       5   

      stalk-color-below-ring  veil-type  veil-color  ring-number  ring-type  \
0                          7          0           2            1          4   
1                          7          0           2            1          4   
2                          7          0           2            1          4   
3                          7          0           2            1          4   
4                          7          0           2            1          0   
...                      ...        ...         ...          ...        ...   
8119                       5          0           1            1          4   
8120                       5          0           0            1          4   
8121                       5          0           1            1          4   
8122                       7          0           2            1          0   
8123                       5          0           1            1          4   

      spore-print-color  population  habitat  
0                     2           3        5  
1                     3           2        1  
2                     3           2        3  
3                     2           3        5  
4                     3           0        1  
...                 ...         ...      ...  
8119                  0           1        2  
8120                  0           4        2  
8121                  0           1        2  
8122                  7           4        2  
8123                  4           1        2  

[8124 rows x 22 columns]

In [162]:
y

0       1
1       0
2       0
3       1
4       0
       ..
8119    0
8120    0
8121    0
8122    1
8123    0
Name: class, Length: 8124, dtype: int32

In [163]:
df.isnull().sum()

class                       0
cap-shape                   0
cap-surface                 0
cap-color                   0
bruises                     0
odor                        0
gill-attachment             0
gill-spacing                0
gill-size                   0
gill-color                  0
stalk-shape                 0
stalk-root                  0
stalk-surface-above-ring    0
stalk-surface-below-ring    0
stalk-color-above-ring      0
stalk-color-below-ring      0
veil-type                   0
veil-color                  0
ring-number                 0
ring-type                   0
spore-print-color           0
population                  0
habitat                     0
dtype: int64

In [164]:
from sklearn.preprocessing import StandardScaler

In [165]:
scale=StandardScaler()

In [166]:
dfx=scale.fit_transform(x)
dfx


array([[ 1.02971224,  0.14012794, -0.19824983, ..., -0.67019486,
        -0.5143892 ,  2.03002809],
       [ 1.02971224,  0.14012794,  1.76587407, ..., -0.2504706 ,
        -1.31310821, -0.29572966],
       [-2.08704716,  0.14012794,  1.37304929, ..., -0.2504706 ,
        -1.31310821,  0.86714922],
       ...,
       [-0.8403434 ,  0.14012794, -0.19824983, ..., -1.50964337,
        -2.11182722,  0.28570978],
       [-0.21699152,  0.95327039, -0.19824983, ...,  1.42842641,
         0.28432981,  0.28570978],
       [ 1.02971224,  0.14012794, -0.19824983, ...,  0.16925365,
        -2.11182722,  0.28570978]])

In [167]:
dfxp=pd.DataFrame(dfx,columns=x.columns)
dfxp

cap-shape  cap-surface  cap-color   bruises      odor  gill-attachment  \
0      1.029712     0.140128  -0.198250  1.185917  0.881938         0.162896   
1      1.029712     0.140128   1.765874  1.185917 -1.970316         0.162896   
2     -2.087047     0.140128   1.373049  1.185917 -0.544189         0.162896   
3      1.029712     0.953270   1.373049  1.185917  0.881938         0.162896   
4      1.029712     0.140128  -0.591075 -0.843230  0.406562         0.162896   
...         ...          ...        ...       ...       ...              ...   
8119  -0.216992     0.140128  -0.198250 -0.843230  0.406562        -6.138869   
8120   1.029712     0.140128  -0.198250 -0.843230  0.406562        -6.138869   
8121  -0.840343     0.140128  -0.198250 -0.843230  0.406562        -6.138869   
8122  -0.216992     0.953270  -0.198250 -0.843230  1.832689         0.162896   
8123   1.029712     0.140128  -0.198250 -0.843230  0.406562        -6.138869   

      gill-spacing  gill-size  gill-color  stalk-shape  ...  \
0        -0.438864   1.494683   -0.228998    -1.144806  ...   
1        -0.438864  -0.669038   -0.228998    -1.144806  ...   
2        -0.438864  -0.669038    0.053477    -1.144806  ...   
3        -0.438864   1.494683    0.053477    -1.144806  ...   
4         2.278612  -0.669038   -0.228998     0.873511  ...   
...            ...        ...         ...          ...  ...   
8119     -0.438864  -0.669038    1.748325    -1.144806  ...   
8120     -0.438864  -0.669038    1.748325    -1.144806  ...   
8121     -0.438864  -0.669038    0.053477    -1.144806  ...   
8122     -0.438864   1.494683   -1.358896     0.873511  ...   
8123     -0.438864  -0.669038    1.748325    -1.144806  ...   

      stalk-surface-below-ring  stalk-color-above-ring  \
0                     0.586385                0.622441   
1                     0.586385                0.622441   
2                     0.586385                0.622441   
3                     0.586385                0.622441   
4                     0.586385                0.622441   
...                        ...                     ...   
8119                  0.586385               -0.429288   
8120                  0.586385               -0.429288   
8121                  0.586385               -0.429288   
8122                 -0.893053                0.622441   
8123                  0.586385               -0.429288   

      stalk-color-below-ring  veil-type  veil-color  ring-number  ring-type  \
0                   0.631991        0.0    0.142037    -0.256132   0.948081   
1                   0.631991        0.0    0.142037    -0.256132   0.948081   
2                   0.631991        0.0    0.142037    -0.256132   0.948081   
3                   0.631991        0.0    0.142037    -0.256132   0.948081   
4                   0.631991        0.0    0.142037    -0.256132  -1.272216   
...                      ...        ...         ...          ...        ...   
8119               -0.416681        0.0   -3.979055    -0.256132   0.948081   
8120               -0.416681        0.0   -8.100146    -0.256132   0.948081   
8121               -0.416681        0.0   -3.979055    -0.256132   0.948081   
8122                0.631991        0.0    0.142037    -0.256132  -1.272216   
8123               -0.416681        0.0   -3.979055    -0.256132   0.948081   

      spore-print-color  population   habitat  
0             -0.670195   -0.514389  2.030028  
1             -0.250471   -1.313108 -0.295730  
2             -0.250471   -1.313108  0.867149  
3             -0.670195   -0.514389  2.030028  
4             -0.250471   -2.910546 -0.295730  
...                 ...         ...       ...  
8119          -1.509643   -2.111827  0.285710  
8120          -1.509643    0.284330  0.285710  
8121          -1.509643   -2.111827  0.285710  
8122           1.428426    0.284330  0.285710  
8123           0.169254   -2.111827  0.285710  

[8124 rows x 22 columns]

In [168]:
dfxp.skew()

cap-shape                  -0.247052
cap-surface                -0.590859
cap-color                   0.706965
bruises                     0.342750
odor                       -0.080790
gill-attachment            -5.977076
gill-spacing                1.840088
gill-size                   0.825797
gill-color                  0.061410
stalk-shape                -0.271345
stalk-root                  0.947852
stalk-surface-above-ring   -1.098739
stalk-surface-below-ring   -0.757703
stalk-color-above-ring     -1.835434
stalk-color-below-ring     -1.791593
veil-type                   0.000000
veil-color                 -6.946944
ring-number                 2.701657
ring-type                  -0.290018
spore-print-color           0.548426
population                 -1.413096
habitat                     0.985548
dtype: float64

In [170]:
xtrain,xtest,ytrain,ytest=train_test_split(dfxp,y,test_size=.22,random_state=45)

In [171]:
model=[LogisticRegression(),SVC(),DecisionTreeClassifier()]

In [172]:
for m in model:
    m.fit(xtrain,ytrain)
    m.score(xtrain,ytrain)
    predm=m.predict(xtest)
    print('accuracy score of ',m,'is',accuracy_score(ytest,predm))
    print(confusion_matrix(ytest,predm))
    print(classification_report(ytest,predm))
    print('\n')

accuracy score of  LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False) is 0.959731543624161
[[897  37]
 [ 35 819]]
              precision    recall  f1-score   support

           0       0.96      0.96      0.96       934
           1       0.96      0.96      0.96       854

    accuracy                           0.96      1788
   macro avg       0.96      0.96      0.96      1788
weighted avg       0.96      0.96      0.96      1788



accuracy score of  SVC(C=1.0, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='rbf',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False) is 1.0
[[934 

In [173]:
from sklearn.model_selection import cross_val_score

In [174]:
lr=LogisticRegression()
lrscores=cross_val_score(lr,dfxp,y,cv=5)
print(lrscores)
print(lrscores.mean(),lrscores.std())

[0.67876923 0.98215385 0.87569231 0.99815385 0.61576355]
0.8301065555134521 0.1563855764003133


In [175]:
svc=SVC()
svcscores=cross_val_score(svc,dfxp,y,cv=5)
print(svcscores)
print(svcscores.mean(),svcscores.std())

[0.84246154 1.         0.96       1.         0.54864532]
0.8702213717317167 0.1708373214891567


In [176]:
dtc=DecisionTreeClassifier()
dtcscores=cross_val_score(dtc,dfxp,y,cv=5)
print(dtcscores)
print(dtcscores.mean(),dtcscores.std())

[0.88184615 1.         0.99753846 1.         0.65517241]
0.9069114058355436 0.13382452908510073


In [177]:
dtc.fit(xtrain,ytrain)
predlr=dtc.predict(xtest)
y_pred_prob=dtc.predict_proba(xtest)[:,1]
print(y_pred_prob)

[0. 0. 1. ... 0. 1. 1.]


In [178]:
from sklearn.externals import joblib
joblib.dump(dtc,'dtcfile.obj')
dtc_from_joblib=joblib.load('dtcfile.obj')
dtc_from_joblib.predict(xtest)

array([0, 0, 1, ..., 0, 1, 1])